source("E:/SEMESTER_4/Thesis/Rwork/loadingPKGS.R")
setwd("E:/SEMESTER_4/REDDPACdata/reddpacDS")
csvData <- read.csv("New folder/simUDataset.csv")
summary(csvData)
origVars.csv <- read.csv("E:/SEMESTER_4/Thesis/Rwork/origVars.csv")
summary(origVars.csv) 
logVars.csv <- read.csv("E:/SEMESTER_4/Thesis/Rwork/logVars.csv")
DVlogVars.csv <- read.csv("E:/SEMESTER_4/Thesis/Rwork/DVlogVars.csv")
summary(DVlogVars.csv)

####################################################
###########forward variable selection###############
####################################################

##############Single variable models################
#untransformed variables
fit1 <- lm(csvData$defor_all~csvData$pasture, data=csvData)
anova(fit1 <- lm(csvData$defor_all~csvData$pasture, data=csvData))
aic1 <- AIC(fit1)
fit2 <- lm(csvData$defor_all~csvData$fra_crplnd, data=csvData)
anova(fit2)
aic2 <-AIC(fit2)
fit3 <- lm(csvData$defor_all~csvData$fra_PAs, data=csvData)
anova(fit3)
aic3 <- AIC(fit3)
fit4 <- lm(csvData$defor_all~csvData$cornpl, data=csvData)
anova(fit4)
aic4 <- AIC(fit4)
fit5 <- lm(csvData$defor_all~csvData$soypl, data=csvData)
anova(fit5)
aic5 <- AIC(fit5)
fit6 <- lm(csvData$defor_all~csvData$sugarcpl, data=csvData)
anova(fit6)
aic6 <- AIC(fit6)
fit7 <- lm(csvData$defor_all~csvData$secVeg, data=csvData)
anova(fit7)
aic7 <- AIC(fit7)
fit8 <- lm(csvData$defor_all~csvData$areaBurnt, data=csvData)
anova(fit8)
aic8 <- AIC(fit8)
fit9 <- lm(csvData$defor_all~csvData$areaRefor, data=csvData)
anova(fit9)
aic9 <- AIC(fit9)
fit10 <- lm(csvData$defor_all~csvData$modUrban, data=csvData)
anova(fit10)
aic10 <- AIC(fit10)
fit11 <- lm(csvData$defor_all~csvData$areaMining, data=csvData)
anova(fit11)
aic11 <- AIC(fit11)

aicSInVarUT <- data.frame(aic1,aic2,aic3,aic4,aic5,aic6,aic7,aic8,aic9,aic10,aic11)

summary(aicSInVarUT)
#write.csv(aicSInVar, "E:/SEMESTER_4/Thesis/Rwork/aicSInVar.csv")

#transformed variables

fit1 <- lm(csvData$logDeforal~csvData$logPasture, data=csvData)
anova(fit1 <- lm(csvData$logDeforal~csvData$logPasture, data=csvData))
aic1 <- AIC(fit1)
fit2 <- lm(csvData$logDeforal~csvData$logpcrplnd, data=csvData)
anova(fit2)
aic2 <-AIC(fit2)
fit3 <- lm(csvData$logDeforal~csvData$logpPA, data=csvData)
anova(fit3)
aic3 <- AIC(fit3)
fit4 <- lm(csvData$logDeforal~csvData$logCornpl, data=csvData)
anova(fit4)
aic4 <- AIC(fit4)
fit5 <- lm(csvData$logDeforal~csvData$logSoypl, data=csvData)
anova(fit5)
aic5 <- AIC(fit5)
fit6 <- lm(csvData$logDeforal~csvData$logSugc, data=csvData)
anova(fit6)
aic6 <- AIC(fit6)
fit7 <- lm(csvData$logDeforal~csvData$logSecveg, data=csvData)
anova(fit7)
aic7 <- AIC(fit7)
fit8 <- lm(csvData$logDeforal~csvData$logBurnt, data=csvData)
anova(fit8)
aic8 <- AIC(fit8)
fit9 <- lm(csvData$logDeforal~csvData$logRefor, data=csvData)
anova(fit9)
aic9 <- AIC(fit9)
fit10 <- lm(csvData$logDeforal~csvData$logUrbanBU, data=csvData)
anova(fit10)
aic10 <- AIC(fit10)
fit11 <- lm(csvData$logDeforal~csvData$logMining, data=csvData)
anova(fit11)
aic11 <- AIC(fit11)

aicSInVarT <- data.frame(aic1,aic2,aic3,aic4,aic5,aic6,aic7,aic8,aic9,aic10,aic11)
summary(aicSInVarT)

##############Double variable models################